version: 3

includes:
  server:
    dir: ./server
    taskfile: ./server/Taskfile.yml

tasks:
  lint:
    desc: Lint the codebase
    cmd: bunx biome lint

  lint:fix:
    desc: Fix linting errors
    cmd: bunx biome lint --write

  lint:fix:unsafe:
    desc: Fix linting errors
    cmd: bunx biome lint --write --unsafe

  format:
    desc: Format the codebase
    cmd: bunx biome format

  format:fix:
    desc: Fix formatting errors
    cmd: bunx biome format --write

  format:fix:unsafe:
    desc: Fix formatting errors
    cmd: bunx biome format --write --unsafe

  check:
    desc: Check the codebase for errors
    cmd: bunx biome check

  check:fix:
    desc: Fix codebase errors
    cmd: bunx biome check --write

  check:fix:unsafe:
    desc: Fix codebase errors
    cmd: bunx biome check --write --unsafe
