version: 3

includes:
  server:
    dir: ./server
    taskfile: ./server/Taskfile.yml
  client:
    dir: ./client
    taskfile: ./client/Taskfile.yml

tasks:
  dev:
    desc: Start the development server
    cmds:
      - task: server:db:migrate
      - bun dev

  lint:
    desc: Lint the codebase
    cmd: bun lint

  lint:fix:
    desc: Fix linting errors
    cmd: bun lint:fix

  lint:fix:unsafe:
    desc: Fix linting errors
    cmd: bun lint --write --unsafe

  format:
    desc: Format the codebase
    cmd: bun format

  format:fix:
    desc: Fix formatting errors
    cmd: bun format:fix

  format:fix:unsafe:
    desc: Fix formatting errors
    cmd: bun format:fix:unsafe

  check:
    desc: Check the codebase for errors
    cmd: bun check

  check:fix:
    desc: Fix codebase errors
    cmd: bun check:fix

  check:fix:unsafe:
    desc: Fix codebase errors
    cmd: bun check:fix:unsafe

  env:init:
    desc: Initialize environment files from examples
    deps:
      - server:env:init
      - client:env:init
