version: "3"

tasks:
  db:generate:
    desc: Generate database schema files
    cmds:
      - bunx drizzle-kit generate

  db:migrate:
    desc: Run database migrations
    cmds:
      - bunx drizzle-kit migrate

  db:seed:
    desc: Run database seed
    cmds:
      - bunx drizzle-seed

  env:init:
    desc: Initialize .env file from example
    status:
      - test -f .env
    cmd: |
      cp .env.example .env
      echo "✅ Created .env from example"
